# Generated by Django 2.2.5 on 2019-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20191021_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
